#!/usr/bin/env bash

set -euo pipefail

readonly EXPECTED_SUBSCRIPTION_ID="e105e38a-7820-4c7e-b1da-de05227d6355"
readonly EXPECTED_TENANT_ID="043348b8-3c3a-488d-a337-62a7ce2e4ae8"
readonly RESOURCE_GROUP="tastematcher-prd-rg"
readonly CONTAINER_APP_NAME="tastematcher-prd-api-ca"
readonly FUNCTIONAPP_NAME="tastematcher-prd-flex"
readonly ACKNOWLEDGEMENT="I_UNDERSTAND_THIS_USES_PRODUCTION_DATA"
readonly REQUESTED_ENVIRONMENT="${1:-prd}"
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPOSITORY_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
readonly WEBAPI_OUTPUT_FILE="${REPOSITORY_ROOT}/webapi/.env.local-production"
readonly FUNCTIONS_OUTPUT_FILE="${REPOSITORY_ROOT}/functions/local.settings.json"

if [[ "${REQUESTED_ENVIRONMENT}" != "prd" ]]; then
  echo "Refusing unknown environment '${REQUESTED_ENVIRONMENT}'. Only 'prd' is supported." >&2
  exit 2
fi

for command_name in az jq; do
  if ! command -v "${command_name}" >/dev/null 2>&1; then
    echo "Required command '${command_name}' is not installed." >&2
    exit 1
  fi
done

"${SCRIPT_DIR}/ensure-production-azure-login.sh"

active_subscription_id="$(az account show --query id --output tsv)"
active_tenant_id="$(az account show --query tenantId --output tsv)"
if [[ "${active_subscription_id}" != "${EXPECTED_SUBSCRIPTION_ID}" ]]; then
  echo "Wrong Azure subscription selected after authentication. Expected ${EXPECTED_SUBSCRIPTION_ID}." >&2
  exit 1
fi
if [[ "${active_tenant_id}" != "${EXPECTED_TENANT_ID}" ]]; then
  echo "Wrong Azure tenant selected after authentication. Expected ${EXPECTED_TENANT_ID}." >&2
  exit 1
fi

containerapp_id="$(az containerapp show \
  --subscription "${EXPECTED_SUBSCRIPTION_ID}" \
  --resource-group "${RESOURCE_GROUP}" \
  --name "${CONTAINER_APP_NAME}" \
  --query id \
  --output tsv)"
if [[ "${containerapp_id}" != "/subscriptions/${EXPECTED_SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.App/containerApps/${CONTAINER_APP_NAME}" ]]; then
  echo "Production Container App identity did not match the expected resource." >&2
  exit 1
fi

functionapp_id="$(az functionapp show \
  --subscription "${EXPECTED_SUBSCRIPTION_ID}" \
  --resource-group "${RESOURCE_GROUP}" \
  --name "${FUNCTIONAPP_NAME}" \
  --query id \
  --output tsv)"
if [[ "${functionapp_id}" != "/subscriptions/${EXPECTED_SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.Web/sites/${FUNCTIONAPP_NAME}" ]]; then
  echo "Production Function App identity did not match the expected resource." >&2
  exit 1
fi

umask 077
webapi_settings_file="$(mktemp "${TMPDIR:-/tmp}/tastematcher-webapi-appsettings.XXXXXX")"
webapi_environment_file="$(mktemp "${TMPDIR:-/tmp}/tastematcher-webapi-environment.XXXXXX")"
webapi_secrets_file="$(mktemp "${TMPDIR:-/tmp}/tastematcher-webapi-secrets.XXXXXX")"
functions_settings_file="$(mktemp "${TMPDIR:-/tmp}/tastematcher-functions-appsettings.XXXXXX")"
generated_webapi_file="$(mktemp "${REPOSITORY_ROOT}/webapi/.env.local-production.XXXXXX")"
generated_functions_file="$(mktemp "${REPOSITORY_ROOT}/functions/local.settings.XXXXXX")"
cleanup() {
  rm -f \
    "${webapi_settings_file}" \
    "${webapi_environment_file}" \
    "${webapi_secrets_file}" \
    "${functions_settings_file}" \
    "${generated_webapi_file}" \
    "${generated_functions_file}"
}
trap cleanup EXIT

az containerapp show \
  --subscription "${EXPECTED_SUBSCRIPTION_ID}" \
  --resource-group "${RESOURCE_GROUP}" \
  --name "${CONTAINER_APP_NAME}" \
  --query 'properties.template.containers[0].env' \
  --output json >"${webapi_environment_file}"

az containerapp secret list \
  --subscription "${EXPECTED_SUBSCRIPTION_ID}" \
  --resource-group "${RESOURCE_GROUP}" \
  --name "${CONTAINER_APP_NAME}" \
  --output json >"${webapi_secrets_file}"

jq -s '
  .[0] as $environment | .[1] as $secrets |
  [$environment[] | . as $entry | {
    name: $entry.name,
    value: (if $entry.secretRef then
      ($secrets[] | select(.name == $entry.secretRef) | .value)
    else $entry.value end)
  }]
' "${webapi_environment_file}" "${webapi_secrets_file}" >"${webapi_settings_file}"

az functionapp config appsettings list \
  --subscription "${EXPECTED_SUBSCRIPTION_ID}" \
  --resource-group "${RESOURCE_GROUP}" \
  --name "${FUNCTIONAPP_NAME}" \
  --output json >"${functions_settings_file}"

readonly REQUIRED_SETTINGS=(
  AZURE_STORAGE_ACCOUNT
  AZURE_STORAGE_ACCOUNT_KEY
  AzureWebJobsStorage
  IMAGE_PROCESSING_QUEUE_NAME
  NEW_ARTWORK_QUEUE_NAME
  COSMOS_DB_ENDPOINT
  COSMOS_DB_KEY
  COSMOS_DB_DATABASE
  AZURE_AI_VISION_ENDPOINT
  AZURE_AI_VISION_KEY
  AZURE_COMMUNICATION_CONNECTION_STRING
  AZURE_EMAIL_SENDER
  JWT_SECRET
)

{
  echo "# Generated by scripts/azure/sync-local-production-config.sh"
  echo "# Contains production credentials. Never commit or share this file."
  echo "NODE_ENV=development"
  echo "TASTEMATCHER_RUNTIME_MODE=local-production"
  echo "TASTEMATCHER_DATA_ENV=prd"
  echo "TASTEMATCHER_LOCAL_PROD_ACK=${ACKNOWLEDGEMENT}"
  echo "TASTEMATCHER_EMAIL_MODE=verification-only"
  echo "PORT=8080"
  echo "CORS_ORIGINS=\"http://localhost:3000,http://localhost:5173\""
  echo "BACKEND_API_URL=\"http://localhost:8080\""
  echo "FRONTEND_URL=\"http://localhost:3000\""
} >"${generated_webapi_file}"

for setting_name in "${REQUIRED_SETTINGS[@]}"; do
  setting_value="$(
    jq -er --arg name "${setting_name}" \
      '[.[] | select(.name == $name) | .value] | if length == 1 and (.[0] | type) == "string" and (.[0] | length) > 0 then .[0] else error("missing") end' \
      "${webapi_settings_file}"
  )" || {
    echo "Required production app setting '${setting_name}' is missing or ambiguous." >&2
    exit 1
  }
  printf '%s=%s\n' "${setting_name}" "$(printf '%s' "${setting_value}" | jq -Rs .)" >>"${generated_webapi_file}"
done

readonly REQUIRED_FUNCTION_SETTINGS=(
  AzureWebJobsStorage
  AZURE_STORAGE_ACCOUNT
  AZURE_STORAGE_ACCOUNT_KEY
  IMAGE_PROCESSING_QUEUE_NAME
  NEW_ARTWORK_QUEUE_NAME
  AZURE_AI_VISION_ENDPOINT
  AZURE_AI_VISION_KEY
  COSMOS_DB_ENDPOINT
  COSMOS_DB_KEY
  COSMOS_DB_DATABASE
  AZURE_COMMUNICATION_CONNECTION_STRING
  AZURE_EMAIL_SENDER
)

for setting_name in "${REQUIRED_FUNCTION_SETTINGS[@]}"; do
  if ! jq -e --arg name "${setting_name}" \
    '[.[] | select(.name == $name) | .value] | length == 1 and (.[0] | type) == "string" and (.[0] | length) > 0' \
    "${functions_settings_file}" >/dev/null; then
    echo "Required production Function App setting '${setting_name}' is missing or ambiguous." >&2
    exit 1
  fi
done

required_function_settings_json="$(printf '%s\n' "${REQUIRED_FUNCTION_SETTINGS[@]}" | jq -R . | jq -s .)"
jq -e \
  --arg acknowledgement "${ACKNOWLEDGEMENT}" \
  --argjson required "${required_function_settings_json}" \
  '
    (reduce .[] as $setting ({}; .[$setting.name] = $setting.value)) as $all |
    ($all | with_entries(select(.key as $key | $required | index($key)))) as $selected |
    {
      IsEncrypted: false,
      Values: ($selected + {
        FUNCTIONS_WORKER_RUNTIME: "node",
        WEBSITE_NODE_DEFAULT_VERSION: "~24",
        FUNCTIONS_EXTENSION_VERSION: "~4",
        NODE_ENV: "development",
        TASTEMATCHER_RUNTIME_MODE: "local-production",
        TASTEMATCHER_DATA_ENV: "prd",
        TASTEMATCHER_LOCAL_PROD_ACK: $acknowledgement,
        FRONTEND_URL: "http://localhost:3000",
        "AzureWebJobs.ProcessImagesFromBlob.Disabled": "true",
        "AzureWebJobs.NotifyUsersNewArtwork.Disabled": "true",
        "AzureWebJobs.DailyDomainOwnerSummary.Disabled": "true"
      })
    }
  ' "${functions_settings_file}" >"${generated_functions_file}"

chmod 600 "${generated_webapi_file}" "${generated_functions_file}"
mv -f "${generated_webapi_file}" "${WEBAPI_OUTPUT_FILE}"
mv -f "${generated_functions_file}" "${FUNCTIONS_OUTPUT_FILE}"
chmod 600 "${WEBAPI_OUTPUT_FILE}" "${FUNCTIONS_OUTPUT_FILE}"

echo "Created protected local-production Web API configuration at webapi/.env.local-production."
echo "Created protected local-production Functions configuration at functions/local.settings.json."
echo "Production values were not printed. Treat these files as secrets."
